"""
NestMatch seed data — 10 Sydney properties with pre-computed feature scores.

Properties cover a realistic spread of suburbs, prices, sizes, commute times,
and lifestyle attributes to validate ranking behaviour across varied criteria.
"""

SEED_PROPERTIES = [
    {
        "id": "prop-001",
        "title": "Spacious apartment in Chatswood",
        "suburb": "Chatswood",
        "price_min": 1180000,
        "price_max": 1280000,
        "bedrooms": 2,
        "internal_size_sqm": 105,
        "property_type": "apartment",
        "parking_spaces": 1,
        "is_new_build": False,
        # Derived features
        "commute_cbd_mins": 31,
        "distance_to_station_m": 420,
        "transport_score": 0.88,
        "school_score": 0.82,
        "noise_score": 0.60,       # 1 = very quiet, 0 = very noisy
        "lifestyle_family_score": 0.78,
    },
    {
        "id": "prop-002",
        "title": "Modern 2-bed in Epping",
        "suburb": "Epping",
        "price_min": 950000,
        "price_max": 1050000,
        "bedrooms": 2,
        "internal_size_sqm": 98,
        "property_type": "apartment",
        "parking_spaces": 1,
        "is_new_build": False,
        "commute_cbd_mins": 42,
        "distance_to_station_m": 280,
        "transport_score": 0.82,
        "school_score": 0.85,
        "noise_score": 0.78,
        "lifestyle_family_score": 0.80,
    },
    {
        "id": "prop-003",
        "title": "Large apartment in Burwood",
        "suburb": "Burwood",
        "price_min": 920000,
        "price_max": 1020000,
        "bedrooms": 3,
        "internal_size_sqm": 118,
        "property_type": "apartment",
        "parking_spaces": 1,
        "is_new_build": False,
        "commute_cbd_mins": 28,
        "distance_to_station_m": 350,
        "transport_score": 0.84,
        "school_score": 0.72,
        "noise_score": 0.55,
        "lifestyle_family_score": 0.70,
    },
    {
        "id": "prop-004",
        "title": "New build apartment in Parramatta",
        "suburb": "Parramatta",
        "price_min": 780000,
        "price_max": 880000,
        "bedrooms": 2,
        "internal_size_sqm": 82,
        "property_type": "apartment",
        "parking_spaces": 1,
        "is_new_build": True,
        "commute_cbd_mins": 45,
        "distance_to_station_m": 180,
        "transport_score": 0.91,
        "school_score": 0.65,
        "noise_score": 0.42,       # busy urban centre
        "lifestyle_family_score": 0.60,
    },
    {
        "id": "prop-005",
        "title": "Quiet apartment in Mascot",
        "suburb": "Mascot",
        "price_min": 1050000,
        "price_max": 1150000,
        "bedrooms": 2,
        "internal_size_sqm": 92,
        "property_type": "apartment",
        "parking_spaces": 1,
        "is_new_build": False,
        "commute_cbd_mins": 20,
        "distance_to_station_m": 450,
        "transport_score": 0.80,
        "school_score": 0.58,
        "noise_score": 0.45,       # airport noise proximity
        "lifestyle_family_score": 0.55,
    },
    {
        "id": "prop-006",
        "title": "Family apartment in Lane Cove",
        "suburb": "Lane Cove",
        "price_min": 1200000,
        "price_max": 1350000,
        "bedrooms": 3,
        "internal_size_sqm": 125,
        "property_type": "apartment",
        "parking_spaces": 2,
        "is_new_build": False,
        "commute_cbd_mins": 33,
        "distance_to_station_m": 950,   # bus-dependent
        "transport_score": 0.62,
        "school_score": 0.90,
        "noise_score": 0.88,
        "lifestyle_family_score": 0.92,
    },
    {
        "id": "prop-007",
        "title": "Compact apartment in Ashfield",
        "suburb": "Ashfield",
        "price_min": 890000,
        "price_max": 980000,
        "bedrooms": 2,
        "internal_size_sqm": 80,
        "property_type": "apartment",
        "parking_spaces": 1,
        "is_new_build": False,
        "commute_cbd_mins": 22,
        "distance_to_station_m": 310,
        "transport_score": 0.86,
        "school_score": 0.68,
        "noise_score": 0.52,
        "lifestyle_family_score": 0.62,
    },
    {
        "id": "prop-008",
        "title": "Affordable house in Penrith",
        "suburb": "Penrith",
        "price_min": 820000,
        "price_max": 920000,
        "bedrooms": 3,
        "internal_size_sqm": 155,
        "property_type": "house",
        "parking_spaces": 2,
        "is_new_build": False,
        "commute_cbd_mins": 65,
        "distance_to_station_m": 600,
        "transport_score": 0.65,
        "school_score": 0.70,
        "noise_score": 0.82,
        "lifestyle_family_score": 0.75,
    },
    {
        "id": "prop-009",
        "title": "Premium apartment in Chatswood",
        "suburb": "Chatswood",
        "price_min": 1350000,
        "price_max": 1450000,
        "bedrooms": 3,
        "internal_size_sqm": 138,
        "property_type": "apartment",
        "parking_spaces": 2,
        "is_new_build": True,
        "commute_cbd_mins": 29,
        "distance_to_station_m": 380,
        "transport_score": 0.90,
        "school_score": 0.85,
        "noise_score": 0.62,
        "lifestyle_family_score": 0.80,
    },
    {
        "id": "prop-010",
        "title": "Mid-size apartment in Epping",
        "suburb": "Epping",
        "price_min": 1020000,
        "price_max": 1120000,
        "bedrooms": 3,
        "internal_size_sqm": 112,
        "property_type": "apartment",
        "parking_spaces": 1,
        "is_new_build": False,
        "commute_cbd_mins": 40,
        "distance_to_station_m": 290,
        "transport_score": 0.83,
        "school_score": 0.88,
        "noise_score": 0.80,
        "lifestyle_family_score": 0.83,
    },
]
